// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI_h4v-9yGBpM18mjQMD-H1qMY6VCwOz8',
    appId: '1:518829323508:web:24ea2f992fdd616b951aa1',
    messagingSenderId: '518829323508',
    projectId: 'canon-assets',
    authDomain: 'canon-assets.firebaseapp.com',
    storageBucket: 'canon-assets.appspot.com',
    measurementId: 'G-7W3SLSTD6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgn1JJw7Zxhvu1-WBnvMUoF3hDlxSKRY',
    appId: '1:518829323508:android:7b5a0eaa1dcddfcc951aa1',
    messagingSenderId: '518829323508',
    projectId: 'canon-assets',
    storageBucket: 'canon-assets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZh8L03iuNWQYiMRiQEx18CmToollaa4c',
    appId: '1:518829323508:ios:d962ac4bb3d5b9d7951aa1',
    messagingSenderId: '518829323508',
    projectId: 'canon-assets',
    storageBucket: 'canon-assets.appspot.com',
    iosClientId: '518829323508-pr8q4gqp2inod891m1u9tek08kq967ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.assetsManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZh8L03iuNWQYiMRiQEx18CmToollaa4c',
    appId: '1:518829323508:ios:d962ac4bb3d5b9d7951aa1',
    messagingSenderId: '518829323508',
    projectId: 'canon-assets',
    storageBucket: 'canon-assets.appspot.com',
    iosClientId: '518829323508-pr8q4gqp2inod891m1u9tek08kq967ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.assetsManagement',
  );
}
